### ISSUE TITLE
[BUG] GPU displayed twice

### ISSUE THREAD

**Issue by zerox003** [fastfetch-cli/fastfetch#1920]
### Read the FAQ first

- [x] I have checked the FAQ but the issue is not covered

### Description

The gpu module in my config displays the gpu twice

### Version used

fastfetch 2.49.0 (x86_64)

### Bug prevalence

Always

### Regression

Yes

### Installation

Package manager

### Package manager

scoop

### Screenshots

<img width="673" height="39" alt="Image" src="https://github.com/user-attachments/assets/ea128084-418b-4ba5-ba0d-f0cdaeaea5f6" />

### Configuration

```jsonc
"modules": [
"gpu"
]
```

### System information

```jsonc
too long for cmd
```

### Features built-in

```text
threads
vulkan
imagemagick7
zlib
opencl
```

**Comment by CarterLi** [comment]
This bug should have been fixed in 2.50.2  You should test it.

Please reopen this bug if 2.50.2 doesn't work.

**Comment by zerox003** [comment]
> This bug should have been fixed in 2.50.2 You should test it.
> 
> Please reopen this bug if 2.50.2 doesn't work.



Bug still exists after updating to `fastfetch 2.50.2 (x86_64)`

I do not have the permissions to reopen @CarterLi

**Comment by CarterLi** [comment]
Hello. Please download this file, run it with `fastfetch -s gpu --debug --format json` and post the output here.

https://nightly.link/CarterLi/fastfetch/workflows/ci/dev/fastfetch-windows-amd64.zip

**Comment by zerox003** [comment]
```json
[gpu_windows.c  24, 12:10:04.170] Starting GPU detection
[gpu_windows.c  33, 12:10:04.178] Found device ID list size: 82
[gpu_windows.c  46, 12:10:04.185] Processing device ID: ROOT\DISPLAY\0000
[gpu_windows.c  62, 12:10:04.191] Device instance ID: 1
[gpu_windows.c  67, 12:10:04.199] Added GPU #1 to list
[gpu_windows.c  91, 12:10:04.205] Failed to parse PCI device information from instance ID
[gpu_windows.c 115, 12:10:04.216] Failed to get PCI bus number
[gpu_windows.c 126, 12:10:04.223] Opened device node registry key
[gpu_windows.c 131, 12:10:04.231] Found VideoID: {6E7F7740-1BF4-11F0-BA18-70321790B3B0}
[gpu_windows.c 136, 12:10:04.240] Opened DirectX registry key
[gpu_windows.c 143, 12:10:04.247] Found vendor ID from DirectX registry: 0x10de
[gpu_windows.c 149, 12:10:04.255] Found GPU description: NVIDIA GeForce RTX 3080 Ti
[gpu_windows.c 152, 12:10:04.265] Found dedicated video memory: 12673089536 bytes
[gpu_windows.c 156, 12:10:04.275] Found dedicated system memory: 0 bytes
[gpu_windows.c 161, 12:10:04.282] Added shared system memory: 17132810240 bytes, total shared: 17132810240 bytes
[gpu_windows.c 167, 12:10:04.296] Found adapter LUID: 121035
[gpu_windows.c 174, 12:10:04.303] Found D3D12 feature level: 0xc200
[gpu_windows.c 186, 12:10:04.312] Found driver version: 9007199255732129
[gpu_windows.c 329, 12:10:04.319] Trying to determine GPU type using D3DKMT APIs
[gpu_windows.c 339, 12:10:04.329] Successfully opened adapter from LUID
[gpu_windows.c 350, 12:10:04.337] Queried adapter type - HybridDiscrete: 0, HybridIntegrated: 0
[gpu_windows.c 363, 12:10:04.349] Trying to get GPU frequency information
[gpu_windows.c 394, 12:10:04.359] Found GPU frequency: 2145 MHz
[gpu_windows.c 407, 12:10:04.366] Closed adapter handle
[gpu_windows.c 447, 12:10:04.373] Using fallback GPU type detection
[gpu_windows.c 456, 12:10:04.381] GPU type determined by memory size (12673089536 bytes): Discrete
[gpu_windows.c 464, 12:10:04.393] Completed processing GPU #1 - Vendor: NVIDIA, Name: NVIDIA GeForce RTX 3080 Ti, Type: 3
[gpu_windows.c  46, 12:10:04.406] Processing device ID: PCI\VEN_10DE&DEV_2208&SUBSYS_389B1462&REV_A1\4&2ae1b128&0&0019
[gpu_windows.c  62, 12:10:04.420] Device instance ID: 2
[gpu_windows.c  67, 12:10:04.427] Added GPU #2 to list
[gpu_windows.c  86, 12:10:04.434] Parsed PCI IDs - Vendor: 0x10de, Device: 0x2208, SubSystem: 0x389b1462, Rev: 0xa1
[gpu_windows.c 106, 12:10:04.447] PCI location - Bus: 9, Device: 0, Function: 0, DeviceID: 9000
[gpu_windows.c 126, 12:10:04.459] Opened device node registry key
[gpu_windows.c 131, 12:10:04.468] Found VideoID: {49EEEFF1-B935-11EF-B95C-C6347071CBB2}
[gpu_windows.c 136, 12:10:04.477] Opened DirectX registry key
[gpu_windows.c 149, 12:10:04.486] Found GPU description: NVIDIA GeForce RTX 3080 Ti
[gpu_windows.c 152, 12:10:04.494] Found dedicated video memory: 12673089536 bytes
[gpu_windows.c 156, 12:10:04.503] Found dedicated system memory: 0 bytes
[gpu_windows.c 161, 12:10:04.511] Added shared system memory: 17132810240 bytes, total shared: 17132810240 bytes
[gpu_windows.c 167, 12:10:04.523] Found adapter LUID: 69377
[gpu_windows.c 174, 12:10:04.531] Found D3D12 feature level: 0xc200
[gpu_windows.c 186, 12:10:04.539] Found driver version: 9007199255732129
[gpu_windows.c 329, 12:10:04.547] Trying to determine GPU type using D3DKMT APIs
[gpu_windows.c 339, 12:10:04.557] Successfully opened adapter from LUID
[gpu_windows.c 350, 12:10:04.566] Queried adapter type - HybridDiscrete: 1, HybridIntegrated: 0
[gpu_windows.c 363, 12:10:04.576] Trying to get GPU frequency information
[gpu_windows.c 394, 12:10:04.588] Found GPU frequency: 2145 MHz
[gpu_windows.c 407, 12:10:04.599] Closed adapter handle
[gpu_windows.c 464, 12:10:04.606] Completed processing GPU #2 - Vendor: NVIDIA, Name: NVIDIA GeForce RTX 3080 Ti, Type: 3
[gpu_windows.c 467, 12:10:04.620] GPU detection completed, found 2 devices
[
  {
    "type": "GPU",
    "result": [
      {
        "index": null,
        "coreCount": null,
        "coreUsage": null,
        "memory": {
          "dedicated": {
            "total": 12673089536,
            "used": null
          },
          "shared": {
            "total": 17132810240,
            "used": null
          },
          "type": null
        },
        "driver": "32.0.15.8097",
        "name": "NVIDIA GeForce RTX 3080 Ti",
        "temperature": null,
        "type": "Discrete",
        "vendor": "NVIDIA",
        "platformApi": "Direct3D 12.2",
        "frequency": 2145,
        "deviceId": 121035
      },
      {
        "index": null,
        "coreCount": null,
        "coreUsage": null,
        "memory": {
          "dedicated": {
            "total": 12673089536,
            "used": null
          },
          "shared": {
            "total": 17132810240,
            "used": null
          },
          "type": null
        },
        "driver": "32.0.15.8097",
        "name": "NVIDIA GeForce RTX 3080 Ti",
        "temperature": null,
        "type": "Discrete",
        "vendor": "NVIDIA",
        "platformApi": "Direct3D 12.2",
        "frequency": 2145,
        "deviceId": 9000
      }
    ]
  }
]
```

**Comment by CarterLi** [comment]
The log reports that you have a (virtual?) device called `ROOT\DISPLAY\0000`. Not sure what it is.

Please run `Get-PnpDevice -Class DISPLAY` in powershell and post the result there. It should tell the real name of the virtual? device

**Comment by zerox003** [comment]
```
Status     Class           FriendlyName                                                                     InstanceId
------     -----           ------------                                                                     ----------
OK         Display         Parsec Virtual Display Adapter                                                   ROOT\DISPLAY...
OK         Display         NVIDIA GeForce RTX 3080 Ti                                                       PCI\VEN_10DE...
```

its parsec....

Should I fix that locally or do you want to take that into account?

**Comment by CarterLi** [comment]
Had a fix https://github.com/fastfetch-cli/fastfetch/commit/26253f886365342d77e6024f3770493d60311f80

It should correctly report your virtual adapter now.

**Comment by zerox003** [comment]
thank you for the good support :)
