### ISSUE TITLE
[BUG] Inconsistent logo quality in bash vs. zsh

### ISSUE THREAD

**Issue by jazz-it** [fastfetch-cli/fastfetch#872]
# General description of bug:

* What happened: Running `fastfetch --logo ~/mylogo.png --logo-width 38` yields with different results when running it in bash vs. zsh (check the screenshot below)
* What should happen: Image quality should be consistent
* Fastfetch version used: fastfetch 2.8.7 (x86_64)
* Did it work in an older version: N/A, this is the first version I've used.
* Where did you get the binary: Manjaro's Official Repo (extra)
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? Not sure.

# Often helpful information:

Screenshot:
![icHan5b](https://github.com/fastfetch-cli/fastfetch/assets/411471/74ff8b2a-525a-4eda-8dc1-f6ab346dded9)

The content of the configuration file you use (if any):
```
//Default settings
```

**Comment by CarterLi** [comment]
Seems chafa was used when executing fastfetch in bash. What terminal were you using?

**Comment by jazz-it** [comment]
> What terminal were you using?

`Yakuake` for bash and `Konsole` for zsh.

**Comment by CarterLi** [comment]
Change to `fastfetch --kitty ~/mylogo.png --logo-width 38` should fix this issue

**Comment by jazz-it** [comment]
BTW, I uninstalled fastfetch with chafa, rebooted my system, I ran `fastfetch --logo ~/mylogo.png --logo-width 38` again and found out that the output image is still the same as per my original screenshot above, so it may not be the result of `chafa`. However, `fastfetch --kitty ~/mylogo.png --logo-width 38` does resolve the issue.
